# Derivatives Risk Management Pipeline Configuration
# This YAML file contains all configurable parameters for the pipeline

# Data Configuration
data:
  symbols: ['AAPL', 'MSFT', 'GOOGL', 'TSLA', 'NVDA']  # Stock symbols to analyze
  start_date: '2020-01-01'                              # Analysis start date
  end_date: '2023-12-31'                               # Analysis end date
  use_mock_data: true                                  # Use synthetic data (true) or real market data (false)
  sample_size: 1000                                    # Number of data points for synthetic data

# Model Parameters
models:
  # Black-Scholes Model Configuration
  black_scholes:
    S: 100.0        # Current underlying price
    K: 105.0        # Strike price
    T: 0.25         # Time to expiration (years)
    r: 0.05         # Risk-free rate
    sigma: 0.2      # Volatility

  # Heston Stochastic Volatility Model Configuration
  heston:
    S: 100.0        # Current underlying price
    K: 105.0        # Strike price
    T: 0.25         # Time to expiration (years)
    r: 0.05         # Risk-free rate
    v0: 0.04        # Initial variance
    kappa: 2.0      # Mean reversion speed
    theta: 0.04     # Long-term variance mean
    sigma_v: 0.3    # Volatility of volatility
    rho: -0.5       # Correlation between price and volatility

  # Binomial Tree Model Configuration
  binomial:
    S: 100.0            # Current underlying price
    K: 105.0            # Strike price
    T: 0.25             # Time to expiration (years)
    r: 0.05             # Risk-free rate
    sigma: 0.2          # Volatility
    n_steps: 100        # Number of time steps in tree
    option_type: 'american'  # Option type: 'european' or 'american'

# Risk Management Configuration
risk:
  var_confidence: [0.01, 0.05, 0.10]     # Confidence levels for VaR calculation
  portfolio_weights: null                 # Portfolio weights (null for equal weights)
  lookback_window: 252                    # Number of days for risk calculations
  monte_carlo_simulations: 10000          # Number of MC simulations for VaR

# Multi-Agent Option Pricing Configuration
multi_agent:
  # Enable multi-agent pricing deviation analysis
  enabled: true

  # Market Maker Configuration
  market_makers:
    count: 3                              # Number of market makers
    initial_cash: 2000000.0               # Initial capital per market maker
    max_inventory: 100.0                  # Maximum inventory per option
    risk_aversion: [0.005, 0.01, 0.02]   # Risk aversion levels (low, medium, high)
    base_spread: 0.015                    # Base bid-ask spread (1.5%)
    volatility_adjustment: 0.4            # Spread adjustment for volatility
    inventory_risk_factor: 0.008          # How much inventory affects quotes

  # Arbitrageur Configuration
  arbitrageurs:
    count: 2                              # Number of arbitrageurs
    initial_cash: 5000000.0               # Initial capital per arbitrageur
    deviation_threshold: 0.008            # Minimum deviation to arbitrage (0.8%)
    max_capital_per_trade: 150000.0       # Maximum capital per arbitrage
    max_total_exposure: 1500000.0         # Maximum total exposure
    transaction_costs: 0.0015             # Transaction cost rate (0.15%)
    borrowing_costs: 0.025                # Annual borrowing cost rate
    max_holding_period: 0.083             # Max holding period (~1 month)

  # Noise Trader Configuration
  noise_traders:
    count: 15                             # Number of noise traders
    initial_cash: 400000.0                # Initial capital per noise trader
    behavior_types: ['momentum', 'mean_reversion', 'overconfident', 'herding', 'random']
    trade_frequency: 0.12                 # Base trading probability per period
    trade_size_mean: 8.0                  # Average trade size
    trade_size_std: 4.0                   # Standard deviation of trade size
    overconfidence_factor: 1.4            # Overconfidence multiplier
    volatility_bias: 0.25                 # Attraction to high volatility
    moneyness_bias: 0.15                  # Preference for certain strikes

  # Market Structure Parameters
  market_structure:
    tick_size: 0.01                       # Minimum price increment
    lot_size: 1                           # Minimum trade size
    impact_coefficient: 0.0008            # Price impact per unit flow
    max_spread: 0.15                      # Maximum allowed spread (15%)

  # Simulation Parameters
  simulation:
    time_steps: 100                       # Number of time steps to simulate
    time_horizon: 0.25                    # Total time horizon (years)
    random_seed: 42                       # Random seed for reproducibility
    market_open_probability: 0.95         # Probability market is open each period

  # Risk Analysis Parameters
  risk_analysis:
    confidence_levels: [0.90, 0.95, 0.99, 0.995]  # VaR confidence levels
    hedge_horizons: [1, 5, 10, 21]       # Hedge effectiveness analysis periods
    stress_scenarios:                      # Predefined stress scenarios
      - name: "arbitrage_constraint"
        reduce_arbitrage_capital: 0.3     # Reduce arbitrage capital by 70%
      - name: "noise_trader_surge"
        increase_noise_trader_activity: 3.0  # Triple noise trading
      - name: "market_maker_stress"
        widen_mm_spreads: 2.5             # 2.5x wider spreads
      - name: "combined_stress"
        reduce_arbitrage_capital: 0.5
        increase_noise_trader_activity: 2.0
        widen_mm_spreads: 1.8

# Validation and Testing Configuration
validation:
  train_ratio: 0.7                        # Proportion of data for training
  validation_ratio: 0.2                   # Proportion of data for validation
  test_ratio: 0.1                         # Proportion of data for testing
  cross_validation_folds: 5               # Number of CV folds
  significance_level: 0.05                # Significance level for statistical tests

# Output Configuration
output:
  save_results: true                      # Save results to files
  results_dir: 'pipeline_results'         # Directory for output files
  plot_results: true                      # Generate visualization plots
  generate_report: true                   # Generate comprehensive report

# Advanced Configuration
advanced:
  # Monte Carlo Configuration
  monte_carlo:
    seed: 42                              # Random seed for reproducibility
    antithetic_variates: true             # Use antithetic variates for variance reduction
    control_variates: false               # Use control variates

  # Numerical Methods Configuration
  numerical:
    integration_method: 'simpson'         # Numerical integration method
    tolerance: 1e-8                       # Numerical tolerance
    max_iterations: 1000                  # Maximum iterations for optimization

  # Parallel Processing Configuration
  parallel:
    use_multiprocessing: false            # Enable parallel processing
    n_cores: 4                           # Number of CPU cores to use

# Scenario Analysis Configuration
scenarios:
  # Market Stress Testing
  stress_tests:
    market_crash:
      price_shock: -0.20                  # 20% price drop
      volatility_spike: 2.0               # Volatility doubles

    interest_rate_shock:
      rate_increase: 0.02                 # 200 basis point increase

    volatility_shock:
      volatility_increase: 0.10           # Additional 10% volatility

  # What-if Analysis
  sensitivity_analysis:
    price_range: [80, 120]                # Price range for sensitivity analysis
    volatility_range: [0.10, 0.40]       # Volatility range
    time_range: [0.1, 1.0]               # Time to expiration range

# Model Calibration Configuration
calibration:
  # Optimization settings
  optimization:
    method: 'L-BFGS-B'                    # Optimization algorithm
    max_function_evaluations: 1000        # Maximum function evaluations

  # Heston calibration specific
  heston_calibration:
    initial_params:
      v0: 0.04
      kappa: 2.0
      theta: 0.04
      sigma_v: 0.3
      rho: -0.5
    bounds:
      v0: [0.01, 0.5]
      kappa: [0.1, 10.0]
      theta: [0.01, 0.5]
      sigma_v: [0.1, 2.0]
      rho: [-0.9, 0.9]

# Reporting Configuration
reporting:
  # Report sections to include
  sections:
    - executive_summary
    - data_analysis
    - model_results
    - risk_analysis
    - performance_metrics
    - validation_results
    - conclusions

  # Chart configurations
  charts:
    price_history: true
    returns_distribution: true
    correlation_matrix: true
    var_backtest: true
    performance_attribution: true

  # Export formats
  export_formats: ['pdf', 'html', 'json']

# Logging Configuration
logging:
  level: 'INFO'                           # Logging level: DEBUG, INFO, WARNING, ERROR
  log_file: 'pipeline.log'               # Log file name
  console_output: true                    # Show logs in console
  detailed_timing: false                  # Include detailed timing information